# Generated by Django 3.1.7 on 2021-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
