# Generated by Django 3.1.7 on 2021-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranking', '0002_payment_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer1',
            field=models.CharField(default=2222, max_length=30),
            preserve_default=False,
        ),
    ]
